services:
  minio-local-dev:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: ../.env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ${SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR}:/data
